### ISSUE TITLE
Unable to compile on Mac OS Sierra

### ISSUE THREAD

**Issue by cniedotus** [joonro/BLP-Python#3]
python setup.py build_ext --inplace 

gave the following output:

running build_ext
building '_BLP' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/chengnie/anaconda/include -arch x86_64 -I/Users/chengnie/anaconda/include/python3.5m -c _BLP.c -o build/temp.macosx-10.7-x86_64-3.5/_BLP.o -fopenmp
"TERMCAP", line 20, col 1, terminal 'SC': Missing separator
clang: error: unsupported option '-fopenmp'
error: command 'gcc' failed with exit status 1

Is it because it is a Intel processor on Mac? I saw in the file name has amd64 in it. 

Is there some way I can use it on Mac?

BTW, I really enjoy reading your beautiful code.

**Comment by cniedotus** [comment]
Fixed it.

FIrst of all, the default gcc on MacOS is from Xcode, which does not support openmp. Therefore, I installed a newer (4.8.5) version of gcc using:

`conda install -c anaconda gcc`

Then, I run the installation again:
`python setup.py build_ext --inplace`

It would have the following error:

running build_ext
building '_BLP' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/chengnie/anaconda/include -arch x86_64 -I/Users/chengnie/anaconda/include/python3.5m -c _BLP.c -o build/temp.macosx-10.7-x86_64-3.5/_BLP.o -fopenmp
_BLP.c:453:31: fatal error: numpy/arrayobject.h: No such file or directory
 #include "numpy/arrayobject.h"
                               ^
compilation terminated.
error: command 'gcc' failed with exit status 1

Then I modified the setup.py file by adding the following line to Line 23:

`include_dirs=[numpy.get_include()],`

Now I can install the package and run it without any issue. It was way faster than the Matlab code. Thank you, @joonro !

**Comment by joonro** [comment]
Hi -

Thank you very much for the kind words. I'm glad it was useful for you.
